# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBoDI4oWNJtJ_rZI7WWkowK022Ebxdq0
"""

import streamlit as st
import cv2
import numpy as np
import pytesseract
from PIL import Image
import re
from skimage.filters import threshold_local
import pickle

# Set page configuration
st.set_page_config(
    page_title="Hotel Bill OCR",
    page_icon="🧾",
    layout="wide"
)

# Load the saved model
@st.cache_resource
def load_model():
    try:
        with open('ocr_model.pkl', 'rb') as f:
            model = pickle.load(f)
        return model
    except FileNotFoundError:
        st.error("Model file not found. Please ensure 'ocr_model.pkl' is in the same directory.")
        return None

def preprocess_image(image):
    """Preprocess image using the same pipeline as training"""
    # Convert to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

    # Apply noise reduction
    denoised = cv2.medianBlur(gray, 3)

    # Apply thresholding
    T = threshold_local(denoised, 11, offset=10, method="gaussian")
    binary = (denoised > T).astype("uint8") * 255

    return binary, denoised

def extract_text(image):
    """Extract text using the same configuration as training"""
    custom_config = r'--oem 3 --psm 6 -c tessedit_char_whitelist=0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz$., '
    text = pytesseract.image_to_string(image, config=custom_config)
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'\s\w\s', ' ', text)
    return text

def main():
    st.title("🧾 Hotel Bill OCR Processor")
    st.markdown("Upload a hotel bill image to extract text using our trained OCR model")

    # Load model
    model = load_model()
    if model is None:
        return

    # File uploader
    uploaded_file = st.file_uploader(
        "Choose a hotel bill image",
        type=['jpg', 'jpeg', 'png'],
        help="Upload a clear image of a hotel bill for text extraction"
    )

    if uploaded_file is not None:
        # Display uploaded image
        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Uploaded Image")
            image = Image.open(uploaded_file)
            st.image(image, use_column_width=True)

            # Convert to OpenCV format
            image_cv = np.array(image)
            image_cv = cv2.cvtColor(image_cv, cv2.COLOR_RGB2BGR)
            image_cv = cv2.cvtColor(image_cv, cv2.COLOR_BGR2RGB)

        with col2:
            st.subheader("Processing Options")
            process_option = st.radio(
                "Select processing method:",
                ["Automatic (Recommended)", "Grayscale only", "Binary only"]
            )

            if st.button("Extract Text", type="primary"):
                with st.spinner("Processing image and extracting text..."):
                    # Preprocess image
                    binary_img, gray_img = preprocess_image(image_cv)

                    # Extract text based on selected option
                    if process_option == "Automatic (Recommended)":
                        text_binary = extract_text(binary_img)
                        text_gray = extract_text(gray_img)
                        final_text = text_binary if len(text_binary) > len(text_gray) else text_gray
                        used_method = "Binary" if len(text_binary) > len(text_gray) else "Grayscale"
                    elif process_option == "Grayscale only":
                        final_text = extract_text(gray_img)
                        used_method = "Grayscale"
                    else:
                        final_text = extract_text(binary_img)
                        used_method = "Binary"

                    # Display results
                    st.subheader("📄 Extracted Text")
                    st.info(f"Used method: {used_method}")

                    # Text area for easy copying
                    st.text_area(
                        "Extracted Text",
                        final_text,
                        height=200,
                        help="You can copy the extracted text from here"
                    )

                    # Display processed images
                    st.subheader("🖼️ Processed Images")
                    proc_col1, proc_col2 = st.columns(2)

                    with proc_col1:
                        st.image(gray_img, caption="Grayscale Image", use_column_width=True)

                    with proc_col2:
                        st.image(binary_img, caption="Binary Image", use_column_width=True)

                    # Download extracted text
                    st.download_button(
                        label="📥 Download Extracted Text",
                        data=final_text,
                        file_name="extracted_bill_text.txt",
                        mime="text/plain"
                    )

        # Display model information in sidebar
        with st.sidebar:
            st.header("Model Information")
            st.write(f"**Version:** {model.get('version', '1.0')}")
            st.write("**Preprocessing Steps:**")
            for step in model['processing_pipeline']['preprocessing_steps']:
                st.write(f"- {step}")

            st.write("**OCR Configuration:**")
            st.code(model['processing_pipeline']['ocr_config'])

    else:
        # Show instructions when no file is uploaded
        st.info("👆 Please upload a hotel bill image to get started")

        # Sample usage instructions
        with st.expander("ℹ️ How to get best results"):
            st.markdown("""
            - **Use clear, high-resolution images**
            - **Ensure good lighting** when taking photos
            - **Position the bill straight** and avoid angles
            - **Include the entire bill** in the frame
            - **Avoid shadows and glares** on the bill

            **Supported formats:** JPG, JPEG, PNG
            """)

if __name__ == "__main__":
    # Note: Make sure tesseract is installed on your system
    # On Windows, you might need to specify the path:
    # pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
    main()